### ISSUE TITLE
detecting the sensor

### ISSUE THREAD

**Issue by Krastanov** [wolneykien/xrandr-align#1]
I am trying to run this on the same hardware as you, however the "gravitate" part fails because it can not detect the sensor.

Could you provide the versions of the kernel modules that you are running in order to detect the device. It should be asus-laptop, however in my case the accelerometer is not present.

**Comment by wolneykien** [comment]
Hi!

The "gravitate" part is for gravi-sensor input device that isn't automatically detected, but rather should be configured. See the xrandr-align-gravitate script and its manual page. The gravisensor is an XOrg (XInput) device with multiple axes, connected to one of the nodes in the /dev/input (event\* or js*).  Such devices might not be properly tagged by the udev daemon and in that case should be configured manually via xorg.conf (or xorg.conf.d/somefile). If you don't have nodes in /dev/input that provide appropriate output when the device is rotated (can be tested with simple `cat`), then either some kernel module isn't loaded or the device have no gravisensor at all.

```
Regards, Paul.
```

**Comment by Krastanov** [comment]
Thank you for the information. As I think that I am using the same hardware (Pegatron Lucid), could you also provide some details about your configurations (kernel and module versions, out-of-tree patches, or some information about what you had to configure yourself).

By the way, do you have an amazon wish list or something similar - I can not buy you a beer for creating this software, however I would like to thank you somehow.

**Comment by wolneykien** [comment]
Thanks for your care! However, that work was fully paid. ;)

Here you can find the configuration files for Pegatron:
http://git.altlinux.org/people/manowar/packages/xorg-conf-pegatron-lucid.git

The main issue is the Xorg configuration file (`90-input-pegatron-lucid.conf`) to be placed in the `xorg.conf.d` (or included in the `xorg.conf`). If it will work with your X server version (the "Pegatron Lucid Tablet Accelerometer" appears in the `xinput list`) then it is possible for you to use the "gravitate" facility — just place the `gravitate` (and the `monitor`) configuration file the `/etc/xrandr-align` directory and use `xrandr-align-gravitate` (and `xrandr-align-monitor`) to start the daemon (or the corresponding `*.desktop` files being added to autostart dir).

However, the Xorg server we used for the distro release reported "Segmentation fault" on initialization of the accelerometer device. Looking for the solution I've tested `sensord` version from MeeGo and found it works perfectly with the help of `acpid` to handle the `rotate` event reported by the `asus-laptop` (?) kernel module. The final chain is little bit long, though: `acpid` -> `sensrod` -> `contextKit` -> `xrandr-daemon`. You can find all of them in my personal repo: http://git.altlinux.org/people/manowar/packages/ .

  Regards, Paul.
